### ISSUE TITLE
Error 1140 adding files to database. Fresh DB, MariaDB type

### ISSUE THREAD

**Issue by sixshooterz** [Ewan-Walker/medb#3]
time="2018-06-26T17:24:02-04:00" level=info msg="runtime: loading medb..." version=2.0.7 
time="2018-06-26T17:24:02-04:00" level=error msg="failed to add files" error="Error 1140: In aggregated query without GROUP BY, expression #2 of SELECT list contains nonaggregated column 'mddb.media.status'; this is incompatible with sql_mode=only_full_group_by" 
time="2018-06-26T17:24:02-04:00" level=info msg="manager.refresh: finished processing library path" db="613.749µs" duration=12.240636ms files=533 path="/media/shares/videos/mom-and-shannin-tmp" scan=11.62575ms
——————————-

Files are not added to the database. Fresh config, fresh database. I’m sure it is something simple.

**Comment by sixshooterz** [comment]
Debug logs:

time="2018-06-26T17:34:51-04:00" level=info msg="runtime: loading medb..." version=2.0.7 
time="2018-06-26T17:34:51-04:00" level=debug msg="encoder.worker.1: started, waiting for job." 
time="2018-06-26T17:34:51-04:00" level=debug msg="storage.addfiles: Finished adding files." duration="614.658µs" existed=0 new=0 
time="2018-06-26T17:34:51-04:00" level=error msg="failed to add files" error="Error 1140: In aggregated query without GROUP BY, expression #2 of SELECT list contains nonaggregated column 'mddb.media.status'; this is incompatible with sql_mode=only_full_group_by" 
time="2018-06-26T17:34:51-04:00" level=info msg="manager.refresh: finished processing library path" db="742.57µs" duration=7.368952ms files=533 path="/media/shares/videos/mom-and-shannin-tmp" scan=6.625251ms 
time="2018-06-26T17:34:52-04:00" level=debug msg="storage.getfiles: Finished fetching files" duration="919.806µs" files=0 
time="2018-06-26T17:34:52-04:00" level=debug msg="manager.queue: no file found" 
time="2018-06-26T17:34:54-04:00" level=debug msg="storage.getfiles: Finished fetching files" duration="798.686µs" files=0 
time="2018-06-26T17:34:54-04:00" level=debug msg="manager.queue: no file found" 
time="2018-06-26T17:34:56-04:00" level=info msg="runtime: shutdown requested" 
time="2018-06-26T17:34:56-04:00" level=debug msg="encoder.client: shutdown workers" 
time="2018-06-26T17:34:56-04:00" level=debug msg="path.watcher: stopped watching [/media/shares/videos/mom-and-shannin-tmp]"

**Comment by ewanwalk** [comment]
This was due to a database update which changed a configuration - changing it back resolved the issue.
